// <auto-generated />
using System;
using CoreLearningSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoreLearningSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.AchievementBadge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AchievementType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Criteria")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("SkillTarget")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<double>("Threshold")
                        .HasColumnType("double");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AchievementBadges");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.AnswerOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("AnswerOptions");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.BackgroundJobExecution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("DurationMilliseconds")
                        .HasColumnType("double");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("ExecutionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("FailedCount")
                        .HasColumnType("int");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("ProcessedCount")
                        .HasColumnType("int");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("int");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("BackgroundJobExecutions");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.CertificateTestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CertificateType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LearnerProfileId")
                        .HasColumnType("int");

                    b.Property<double>("MaxScore")
                        .HasColumnType("double");

                    b.Property<bool>("Passed")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("Score")
                        .HasColumnType("double");

                    b.Property<int?>("SourceQuizAttemptId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TakenAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("TargetScore")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("LearnerProfileId");

                    b.ToTable("CertificateTestResults");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminResponse")
                        .HasColumnType("longtext");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LearnerProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewComment")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ReviewedByAdminId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("TargetId")
                        .HasColumnType("int");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("LearnerProfileId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.FeedbackAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AggregateKey")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("AlertStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("AlertedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("AverageRating")
                        .HasColumnType("double");

                    b.Property<int>("FeedbackCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastAnalyzedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastFeedbackAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LowRatingCount")
                        .HasColumnType("int");

                    b.Property<int>("NegativeCount")
                        .HasColumnType("int");

                    b.Property<int>("NeutralCount")
                        .HasColumnType("int");

                    b.Property<int>("PositiveCount")
                        .HasColumnType("int");

                    b.Property<int?>("TargetId")
                        .HasColumnType("int");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AggregateKey")
                        .IsUnique();

                    b.ToTable("FeedbackAnalyses");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.GoalProgressHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AddedValue")
                        .HasColumnType("double");

                    b.Property<int>("GoalId")
                        .HasColumnType("int");

                    b.Property<int>("LearnerProfileId")
                        .HasColumnType("int");

                    b.Property<double>("NewValue")
                        .HasColumnType("double");

                    b.Property<double>("PreviousValue")
                        .HasColumnType("double");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("StatusAfter")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("StatusBefore")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("LearnerProfileId");

                    b.HasIndex("GoalId", "SourceEventId")
                        .IsUnique();

                    b.ToTable("GoalProgressHistories");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.GoalSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("CurrentValue")
                        .HasColumnType("double");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LearnerProfileId")
                        .HasColumnType("int");

                    b.Property<double>("ProgressPercentage")
                        .HasColumnType("double");

                    b.Property<string>("SkillTarget")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TargetLevel")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<double>("TargetValue")
                        .HasColumnType("double");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("LearnerProfileId");

                    b.ToTable("GoalSettings");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.LearnerBadge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BadgeId")
                        .HasColumnType("int");

                    b.Property<int>("LearnerProfileId")
                        .HasColumnType("int");

                    b.Property<double>("ProgressValue")
                        .HasColumnType("double");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.HasIndex("LearnerProfileId", "BadgeId")
                        .IsUnique();

                    b.ToTable("LearnerBadges");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.LearnerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("LastActiveAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("LearnerProfiles");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.LearnerProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastAccessedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LearnerProfileId")
                        .HasColumnType("int");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LearnerProfileId");

                    b.HasIndex("LessonId");

                    b.ToTable("LearnerProgresses");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.LearnerWeaknessHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FirstOccurredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IncorrectCount")
                        .HasColumnType("int");

                    b.Property<Guid>("LastEventId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("LastOccurredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LearnerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("OccurrenceCount")
                        .HasColumnType("int");

                    b.Property<string>("Skill")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("SourceQuizAttemptId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("LearnerProfileId", "Skill", "Topic")
                        .IsUnique();

                    b.ToTable("LearnerWeaknessHistories");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.LearningPath", b =>
                {
                    b.Property<int>("PathId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PathId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("PathId");

                    b.HasIndex("LearnerId")
                        .IsUnique();

                    b.ToTable("LearningPaths");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.LearningPathItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LearningPathId")
                        .HasColumnType("int");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("LearningPathId");

                    b.HasIndex("LessonId");

                    b.ToTable("LearningPathItems");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("QuizId")
                        .HasColumnType("int");

                    b.Property<string>("Skill")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SourceEventId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SourceId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SourceType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.NotificationDeliveryAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("NotificationId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.ToTable("NotificationDeliveryAttempts");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HeadersJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.PlacementTestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LearnerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("RecommendedLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime>("TakenAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("LearnerProfileId");

                    b.ToTable("PlacementTestResults");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<string>("ReadingText")
                        .HasColumnType("longtext");

                    b.Property<double>("Score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double")
                        .HasDefaultValue(1.0);

                    b.Property<string>("Skill")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsPlacementTest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<double>("MaxScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double")
                        .HasDefaultValue(10.0);

                    b.Property<double>("PassingScore")
                        .HasColumnType("double");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.QuizAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CorrectAnswersCount")
                        .HasColumnType("int");

                    b.Property<int>("IncorrectAnswersCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LearnerProfileId")
                        .HasColumnType("int");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<double>("Score")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("LearnerProfileId");

                    b.HasIndex("QuizId");

                    b.ToTable("QuizAttempts");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.QuizAttemptDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("QuizAttemptId")
                        .HasColumnType("int");

                    b.Property<int?>("SelectedAnswerOptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuizAttemptId");

                    b.HasIndex("SelectedAnswerOptionId");

                    b.ToTable("QuizAttemptDetails");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.Recommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DismissedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LearnerProfileId")
                        .HasColumnType("int");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<double>("PriorityScore")
                        .HasColumnType("double");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Skill")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("SourceEventId");

                    b.HasIndex("LearnerProfileId", "LessonId");

                    b.HasIndex("LearnerProfileId", "Status");

                    b.ToTable("Recommendations");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.RecommendationEffectiveness", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Improvement")
                        .HasColumnType("double");

                    b.Property<int>("LearnerProfileId")
                        .HasColumnType("int");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("RecommendationId")
                        .HasColumnType("int");

                    b.Property<double>("ScoreAfter")
                        .HasColumnType("double");

                    b.Property<double>("ScoreBefore")
                        .HasColumnType("double");

                    b.Property<string>("Skill")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("SourceQuizAttemptId")
                        .HasColumnType("int");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("WasEffective")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("LearnerProfileId");

                    b.HasIndex("LessonId");

                    b.HasIndex("RecommendationId");

                    b.ToTable("RecommendationEffectivenesses");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.RecommendationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("LearnerProfileId")
                        .HasColumnType("int");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("RecommendationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LearnerProfileId");

                    b.HasIndex("LessonId");

                    b.HasIndex("RecommendationId");

                    b.HasIndex("RecordedAt");

                    b.HasIndex("SourceEventId");

                    b.ToTable("RecommendationHistories");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.RecommendationStatisticSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageImprovement")
                        .HasColumnType("double");

                    b.Property<int>("CompletionCount")
                        .HasColumnType("int");

                    b.Property<int>("EffectiveCount")
                        .HasColumnType("int");

                    b.Property<double>("EffectivenessRate")
                        .HasColumnType("double");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LessonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RecommendationCount")
                        .HasColumnType("int");

                    b.Property<string>("Skill")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Topic")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("RecommendationStatisticSnapshots");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.SkillMatrix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("CurrentScore")
                        .HasColumnType("double");

                    b.Property<double>("LastAssessmentScore")
                        .HasColumnType("double");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LearnerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("MasteryLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Skill")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("TotalAssessments")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LearnerProfileId", "Skill")
                        .IsUnique();

                    b.ToTable("SkillMatrices");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.SkillMatrixHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AssessmentScore")
                        .HasColumnType("double");

                    b.Property<string>("DecayPeriodKey")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("char(36)");

                    b.Property<int>("LearnerProfileId")
                        .HasColumnType("int");

                    b.Property<double>("NewScore")
                        .HasColumnType("double");

                    b.Property<double>("PreviousScore")
                        .HasColumnType("double");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Skill")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("SkillMatrixId")
                        .HasColumnType("int");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("LearnerProfileId");

                    b.HasIndex("SkillMatrixId", "DecayPeriodKey")
                        .IsUnique();

                    b.ToTable("SkillMatrixHistories");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.UserSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("JwtId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RefreshTokenHash")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SessionTokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JwtId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.WeeklyLearningReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageScore")
                        .HasColumnType("double");

                    b.Property<string>("BadgesEarned")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GoalProgressSummary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("LearnerProfileId")
                        .HasColumnType("int");

                    b.Property<int>("LessonsCompleted")
                        .HasColumnType("int");

                    b.Property<int?>("NotificationId")
                        .HasColumnType("int");

                    b.Property<int>("QuizzesCompleted")
                        .HasColumnType("int");

                    b.Property<int>("RecommendationsCompleted")
                        .HasColumnType("int");

                    b.Property<int>("StreakDays")
                        .HasColumnType("int");

                    b.Property<string>("StrongestSkill")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("WeakestSkill")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("WeekEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("WeekStart")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.HasIndex("LearnerProfileId", "WeekStart")
                        .IsUnique();

                    b.ToTable("WeeklyLearningReports");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.AnswerOption", b =>
                {
                    b.HasOne("CoreLearningSystem.Domain.Entities.Question", "Question")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.CertificateTestResult", b =>
                {
                    b.HasOne("CoreLearningSystem.Domain.Entities.LearnerProfile", "LearnerProfile")
                        .WithMany("CertificateTestResults")
                        .HasForeignKey("LearnerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearnerProfile");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.Feedback", b =>
                {
                    b.HasOne("CoreLearningSystem.Domain.Entities.LearnerProfile", "LearnerProfile")
                        .WithMany("SubmittedFeedbacks")
                        .HasForeignKey("LearnerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearnerProfile");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.GoalProgressHistory", b =>
                {
                    b.HasOne("CoreLearningSystem.Domain.Entities.GoalSetting", "Goal")
                        .WithMany("ProgressHistories")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreLearningSystem.Domain.Entities.LearnerProfile", "LearnerProfile")
                        .WithMany("GoalProgressHistories")
                        .HasForeignKey("LearnerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");

                    b.Navigation("LearnerProfile");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.GoalSetting", b =>
                {
                    b.HasOne("CoreLearningSystem.Domain.Entities.LearnerProfile", "LearnerProfile")
                        .WithMany("Goals")
                        .HasForeignKey("LearnerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearnerProfile");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.LearnerBadge", b =>
                {
                    b.HasOne("CoreLearningSystem.Domain.Entities.AchievementBadge", "Badge")
                        .WithMany("AwardedLearners")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreLearningSystem.Domain.Entities.LearnerProfile", "LearnerProfile")
                        .WithMany("UnlockedBadges")
                        .HasForeignKey("LearnerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("LearnerProfile");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.LearnerProfile", b =>
                {
                    b.HasOne("CoreLearningSystem.Domain.Entities.User", "User")
                        .WithOne("LearnerProfile")
                        .HasForeignKey("CoreLearningSystem.Domain.Entities.LearnerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.LearnerProgress", b =>
                {
                    b.HasOne("CoreLearningSystem.Domain.Entities.LearnerProfile", "LearnerProfile")
                        .WithMany("ProgressHistory")
                        .HasForeignKey("LearnerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreLearningSystem.Domain.Entities.Lesson", "Lesson")
                        .WithMany("ProgressHistory")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LearnerProfile");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.LearnerWeaknessHistory", b =>
                {
                    b.HasOne("CoreLearningSystem.Domain.Entities.LearnerProfile", "LearnerProfile")
                        .WithMany("WeaknessHistories")
                        .HasForeignKey("LearnerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearnerProfile");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.LearningPath", b =>
                {
                    b.HasOne("CoreLearningSystem.Domain.Entities.LearnerProfile", "LearnerProfile")
                        .WithOne("LearningPath")
                        .HasForeignKey("CoreLearningSystem.Domain.Entities.LearningPath", "LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearnerProfile");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.LearningPathItem", b =>
                {
                    b.HasOne("CoreLearningSystem.Domain.Entities.LearningPath", "LearningPath")
                        .WithMany("Items")
                        .HasForeignKey("LearningPathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreLearningSystem.Domain.Entities.Lesson", "Lesson")
                        .WithMany("LearningPathItems")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LearningPath");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("CoreLearningSystem.Domain.Entities.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.Notification", b =>
                {
                    b.HasOne("CoreLearningSystem.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.NotificationDeliveryAttempt", b =>
                {
                    b.HasOne("CoreLearningSystem.Domain.Entities.Notification", "Notification")
                        .WithMany("DeliveryAttempts")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.PlacementTestResult", b =>
                {
                    b.HasOne("CoreLearningSystem.Domain.Entities.LearnerProfile", "LearnerProfile")
                        .WithMany("PlacementTestResults")
                        .HasForeignKey("LearnerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearnerProfile");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.Question", b =>
                {
                    b.HasOne("CoreLearningSystem.Domain.Entities.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.QuizAttempt", b =>
                {
                    b.HasOne("CoreLearningSystem.Domain.Entities.LearnerProfile", "LearnerProfile")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("LearnerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreLearningSystem.Domain.Entities.Quiz", "Quiz")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LearnerProfile");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.QuizAttemptDetail", b =>
                {
                    b.HasOne("CoreLearningSystem.Domain.Entities.Question", "Question")
                        .WithMany("QuizAttemptDetails")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoreLearningSystem.Domain.Entities.QuizAttempt", "QuizAttempt")
                        .WithMany("Details")
                        .HasForeignKey("QuizAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreLearningSystem.Domain.Entities.AnswerOption", "SelectedAnswerOption")
                        .WithMany()
                        .HasForeignKey("SelectedAnswerOptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Question");

                    b.Navigation("QuizAttempt");

                    b.Navigation("SelectedAnswerOption");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.Recommendation", b =>
                {
                    b.HasOne("CoreLearningSystem.Domain.Entities.LearnerProfile", "LearnerProfile")
                        .WithMany("Recommendations")
                        .HasForeignKey("LearnerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreLearningSystem.Domain.Entities.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LearnerProfile");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.RecommendationEffectiveness", b =>
                {
                    b.HasOne("CoreLearningSystem.Domain.Entities.LearnerProfile", "LearnerProfile")
                        .WithMany("RecommendationEffectivenesses")
                        .HasForeignKey("LearnerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreLearningSystem.Domain.Entities.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoreLearningSystem.Domain.Entities.Recommendation", "Recommendation")
                        .WithMany()
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearnerProfile");

                    b.Navigation("Lesson");

                    b.Navigation("Recommendation");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.RecommendationHistory", b =>
                {
                    b.HasOne("CoreLearningSystem.Domain.Entities.LearnerProfile", "LearnerProfile")
                        .WithMany("RecommendationHistories")
                        .HasForeignKey("LearnerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreLearningSystem.Domain.Entities.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoreLearningSystem.Domain.Entities.Recommendation", "Recommendation")
                        .WithMany()
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearnerProfile");

                    b.Navigation("Lesson");

                    b.Navigation("Recommendation");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.RecommendationStatisticSnapshot", b =>
                {
                    b.HasOne("CoreLearningSystem.Domain.Entities.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.SkillMatrix", b =>
                {
                    b.HasOne("CoreLearningSystem.Domain.Entities.LearnerProfile", "LearnerProfile")
                        .WithMany("SkillMatrices")
                        .HasForeignKey("LearnerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearnerProfile");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.SkillMatrixHistory", b =>
                {
                    b.HasOne("CoreLearningSystem.Domain.Entities.LearnerProfile", "LearnerProfile")
                        .WithMany("SkillMatrixHistories")
                        .HasForeignKey("LearnerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearnerProfile");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.UserSession", b =>
                {
                    b.HasOne("CoreLearningSystem.Domain.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.WeeklyLearningReport", b =>
                {
                    b.HasOne("CoreLearningSystem.Domain.Entities.LearnerProfile", "LearnerProfile")
                        .WithMany("WeeklyLearningReports")
                        .HasForeignKey("LearnerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreLearningSystem.Domain.Entities.Notification", "Notification")
                        .WithMany()
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LearnerProfile");

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.AchievementBadge", b =>
                {
                    b.Navigation("AwardedLearners");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.GoalSetting", b =>
                {
                    b.Navigation("ProgressHistories");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.LearnerProfile", b =>
                {
                    b.Navigation("CertificateTestResults");

                    b.Navigation("GoalProgressHistories");

                    b.Navigation("Goals");

                    b.Navigation("LearningPath");

                    b.Navigation("PlacementTestResults");

                    b.Navigation("ProgressHistory");

                    b.Navigation("QuizAttempts");

                    b.Navigation("RecommendationEffectivenesses");

                    b.Navigation("RecommendationHistories");

                    b.Navigation("Recommendations");

                    b.Navigation("SkillMatrices");

                    b.Navigation("SkillMatrixHistories");

                    b.Navigation("SubmittedFeedbacks");

                    b.Navigation("UnlockedBadges");

                    b.Navigation("WeaknessHistories");

                    b.Navigation("WeeklyLearningReports");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.LearningPath", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.Lesson", b =>
                {
                    b.Navigation("LearningPathItems");

                    b.Navigation("ProgressHistory");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.Notification", b =>
                {
                    b.Navigation("DeliveryAttempts");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.Question", b =>
                {
                    b.Navigation("AnswerOptions");

                    b.Navigation("QuizAttemptDetails");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.Quiz", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("QuizAttempts");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.QuizAttempt", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("CoreLearningSystem.Domain.Entities.User", b =>
                {
                    b.Navigation("LearnerProfile");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
